#!/bin/bash

# This script allows the user to connect
# to a wireless network using nmcli

# Print available connections
nmcli dev wifi

echo
echo "Enter SSID:"
read ssid
echo "Enter password:"
read -s password
echo
echo "Connecting to $ssid..."

# Connect to chosen network
nmcli dev wifi connect "$ssid" password "$password"
